models/Bill.php
<?php

namespace app\models;

use Yii;
 
/** 
 * This is the model class for table "bill".
 *
 * @property int $id
 * @property int $consumer_id
 * @property int $total_months_conservancy
 * @property int $water_arrears
 * @property string $water_remarks
 * @property int $conservancy_amount
 * @property int $total_water_and_conservancy_amount
 * @property int $tinure 
 * @property int $dues_amount
 * @property int $per_month_charges
 * @property int $no_of_months
 * @property int $total_amount_of_current_months
 * @property int $advanced_pay
 * @property int $arrears

* @property int $water_bill 
 * @property int $arrears_period
 * @property int $total_bill
 * @property int $after_due_date_charges
 * @property int $total_after_due_date
 * @property int $balance_arears
 * @property string $remarks
 * @property int $conservancy_charges_per_month

 * @property string $billing_months
 * @property string $issue_date
 * @property string $due_date 
  * @property string $cnic
 * @property string $reference_no
 */
class Bill extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public $file;
    public static function tableName()
    {
        return 'bill';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['consumer_id', 'water_arrears',  'conservancy_amount', 'dues_amount',  'arrears', 'arrears_period', 'total_bill', 'after_due_date_charges', 'total_after_due_date', 'issue_date', 'due_date','status'], 'required'],
            [['file'],'file', 'maxFiles'=>1000],
            [['consumer_id', 'total_months_conservancy', 'water_arrears', 'conservancy_amount', 'total_water_and_conservancy_amount', 'tinure', 'dues_amount', 'per_month_charges', 'no_of_months', 'total_amount_of_current_months', 'advanced_pay', 'arrears', 'arrears_period', 'total_bill', 'after_due_date_charges', 'total_after_due_date', 'balance_arears','payment','debit','other_charges'], 'integer'],
            [['issue_date', 'water_bill', 'due_date','created_on','updated_on',  'advanced_pay',  'tinure','billing_months','email','cnic','sector'], 'safe'],
            [['water_remarks','document'], 'string', 'max' => 250],
            [['remarks'], 'string', 'max' => 350],
            [['billing_months'], 'string', 'max' => 255],
            [['reference_no'], 'string', 'max' => 13],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Bill ID',
            'consumer_id' => 'Name',
            'cnic'=>'Cnic',
            'email'=>'Email',
            'total_months_conservancy' => 'Total Months Conservancy',
            'water_arrears' => 'Water Arrears',
            'water_remarks' => 'Water Remarks',
            'conservancy_amount' => 'Conservancy Amount',
            'total_water_and_conservancy_amount' => 'Total Water And Conservancy Amount',
            'tinure' => 'Tinure',
            'sector' => 'Sector',
            'dues_amount' => 'Dues Amount',
            'per_month_charges' => 'Per Month Charges',
            'no_of_months' => 'No Of Months',
            'total_amount_of_current_months' => 'Total Amount Of Current Months',
            'advanced_pay' => 'Advanced Pay',
            'debit' => 'debit Pay',
            'arrears' => 'Arrears',
             'water_bill' => 'water_bill',
            'arrears_period' => 'Arrears Period',
            'total_bill' => 'Total Bill',
            'Status'=>'Status',
            'after_due_date_charges' => 'After Due Date Charges',
            'total_after_due_date' => 'Total After Due Date',
            'balance_arears' => 'Balance Arears',
            'remarks' => 'Remarks',
            'conservancy_charges_per_month' => 'Conservancy Charges Per Month',
            'billing_months' => 'Tenure',
            'issue_date' => 'Issue Date',
            'due_date' => 'Due Date',
            'reference_no' => 'Reference No',
        ];
    }

   
            public function getconsumerId()
            {
                return $this->hasOne(Plot::className(),['id' => 'consumer_id']);
            }

            public function getfileNo()
            {
                return $this->hasOne(Plot::className(),['id' => 'consumer_id']);
            }
            public function getsectorName()
            {
                return $this->hasOne(Sectors::className(),['id' => 'sector']);
            }

            public function getsubsectorName()
            {
                return $this->hasOne(SubSectors::className(),['name' => 'sector']);
            }

            public function gettenureName()
            {
                return $this->hasOne(Tenure::className(),['id' => 'tinure']);
            }    
               


   
}
 

models/BillController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Bill;
use app\models\SubSectors;
use app\models\Sectors;
use app\models\BillSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\Activity; 
use\yii\web\UploadedFile; 

/**
 * BillController implements the CRUD actions for Bill model.
 */
class BillController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        $behaviors['access'] = [
            'class' => AccessControl::className(),
            'rules' => [
                [

                    'allow' => true,
                    'roles' => ['@'],
                    'matchCallback' => function ($rule, $action) {

                        // $module                 = Yii::$app->controller->module->id;
                        $action                 = Yii::$app->controller->action->id;
                        $controller         = Yii::$app->controller->id;
                        $route                     = "$controller/$action";
                        $post = Yii::$app->request->post();


                        if($route=='bill/validate')
                        {
                            return true;
                        }
                        else if (\Yii::$app->user->can($route)) {
                            return true;
                        }


                    }
                ],
            ],
        ];

        return $behaviors;
    }

    /**
     * Lists all Bill models.
     * @return mixed
     */
    public function actionIndex()
    {
      
        $searchModel = new BillSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
         $dataProvider->sort->defaultOrder = ['id' => SORT_DESC];

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Bill model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $this->layout = 'generatebill';

        $model = $this->findModel($id);
        $activitycreate = Yii::$app->user->identity->username.' views the bill of consumer '.$model->consumer_id;
        $activity = New Activity();
        $activit = $activity->activityrecord($activitycreate, true);
        return $this->render('view', [
            'val' => $model, 
        ]);
    }

    public function actionBarcode()
    {
        $model = new Bill();
        $data = '';
        $display = 'none';

        return $this->render('barCode_form', [
            'model' => $model,
            'data1' => $data,
            'dis' => $display,
        ]);

       
    }
 
     public function actionUpdatestatus()
    {

        //$model = new Bill();
        //$a= ($_POST['b_id']);
        $id = $_POST['bill_id'];
        $check = $_POST['check'];

     

        if ($check==0) {
            
        
        
      [$one, $two]=(explode("_", $id));
        //  echo "<pre>";
        // print_r($one);
        // exit;

       
     
        $model=Bill::findOne($one);
        
         
        if($model!= null)
        {
            
            Yii::$app->db->createCommand()->update('bill', ['status' => 1], ['id' =>$one])->execute();
           //Bill::update(['status' => 1], ['like', 'id', $id]);
           //$model->status=1;
           //$('#s-msg').show();
          
           $data = "Record Updated Successfully!";
           $display = "block";
           $t_bill = $model->total_bill;
           $model->payment = $t_bill;

           if($model->save())
           {

            return $this->render('barCode_form', [
                'model' => $model,
                'data1' => $data,
                'dis' => $display,
            ]);
           }
           else
           {

            $data = "Something Went Wrong!";
            $display = "block";

            return $this->render('barCode_form', [
                'model' => $model,
                'data1' => $data,
                'dis' => $display,
            ]);
           }

         }
         else
         {
             $data = "Record Not Found!";
             $display = "block";

             return $this->render('barCode_form', [
                'model' => $model,
                'data1' => $data,
                'dis' => $display,
            ]);
            
         }}else{

      [$one, $two]=(explode("_", $id));

       
     
        $model=Bill::findOne($one);
        
         
        if($model!= null)
        {
            
            Yii::$app->db->createCommand()->update('bill', ['status' => 1], ['id' =>$one])->execute();
           //Bill::update(['status' => 1], ['like', 'id', $id]);
           //$model->status=1;
           //$('#s-msg').show();
          
           $data = "Record Updated Successfully!";
           $display = "block";
           $t_bill = $model->total_after_due_date;
           $model->payment = $t_bill;

           if($model->save())
           {

            return $this->render('barCode_form', [
                'model' => $model,
                'data1' => $data,
                'dis' => $display,
            ]);
           }
           else
           {

            $data = "Something Went Wrong!";
            $display = "block";

            return $this->render('barCode_form', [
                'model' => $model,
                'data1' => $data,
                'dis' => $display,
            ]);
           }

         }
         else
         {
             $data = "Record Not Found!";
             $display = "block";

             return $this->render('barCode_form', [
                'model' => $model,
                'data1' => $data,
                'dis' => $display,
            ]);
            
         }
         }}
        
    
     public function actionSectorPrint()
    {
        
        return $this->render('sectorprint');
    } 

     public function actionUpdateduedate()
    {
          $model = new Bill();           
        if ($model->load(Yii::$app->request->post())) {
            
            
            $model->tinure = $_POST['Bill']['tinure'];
           

            $model->sector=$_POST['Bill']['sector'];

            $due_date = $_POST['due_date'];
             


            \Yii::$app->db->createCommand("UPDATE bill SET due_date= '$due_date'  WHERE tinure='$model->tinure' AND sector='$model->sector'")->execute();
            
        
           
            $model->save();
              
}
    
        return $this->render('updateduedate', [
            'model' => $model,
        ]);
    }
       

    /**
     * Creates a new Bill model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Bill();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $activitycreate = Yii::$app->user->identity->username.' Created the new bill for consumer '.$_POST['Bill']['consumer_id'];

           $activity = New Activity();
        $activit = $activity->activityrecord($activitycreate, true);
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Bill model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
       
        $model = $this->findModel($id);
        $data = "Record Updated Successfully!";
        $display = "block";
        $olds= $model->document;
          // echo "<pre>";
          //           print_r($olds);
                    // exit();
        $old = json_decode($model->document);

        if (!empty($old)) {
           $new = implode(",",$old);

         if ($model->load(Yii::$app->request->post())) {
            $files =  $model->file;
            
            $model->file = UploadedFile::getInstances($model, 'file');
            if (!empty($model->file )) {

            if ($model->file && $model->validate()) {
                foreach ($model->file as $file) {
                   
                   
                $file->saveAs('uploads/' . $file->baseName . '.' . $file->extension);

                $names[]=$file->name;
                $names++;
                $total_names = $names;
                  
                }

                $merge=(array_merge($total_names,$old));
                $name = json_encode($merge);

                $model->document =  $name;
                   if ($model->save()) {
                 Yii::$app->session->setFlash('success', 'Record updated Successfully');
                   
               }
            }}}

    }else{
        


         if ($model->load(Yii::$app->request->post())) {
            $files =  $model->file;
            
            $model->file = UploadedFile::getInstances($model, 'file');
            if (!empty($model->file )) {

            if ($model->file && $model->validate()) {
                foreach ($model->file as $file) {
                    // $i++;   
                $file->saveAs('uploads/' . $file->baseName . '.' . $file->extension);

                $names[]=$file->name;
                $names++;
                $total_names = json_encode($names);
                  
                }
                
                $model->document =  $total_names;
                
             if ($model->save()) {
                  Yii::$app->session->setFlash('success', 'Record updated Successfully');
                   
               } 

  

            }}

views/bill/_billsearch.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Bill;
use app\models\BillSearch;
use yii\helpers\ArrayHelper;
use kartik\daterange\DateRangePicker; 



/* @var $this yii\web\View */
/* @var $model app\models\BillSearch */
/* @var $form yii\widgets\ActiveForm */
?> 

<div class="bill-search">

    <?php $form = ActiveForm::begin([
        'action' => ['bill-report'],
        'method' => 'POST',

    ]); ?>

    <div class="card">
        <div class="row">
            <div class="col-lg-12">

                <div class="row" style="margin: 10px;">


                        <?php // echo $form->field($model, 'consumer_id') ?>

                        

                        <?php // echo $form->field($model, 'total_months_conservancy') ?>

                        <?php //echo $form->field($model, 'water_arrears') ?>

                        <?php // echo $form->field($model, 'water_remarks') ?>

                        

                        <?php // echo $form->field($model, 'cnic') ?>

                        
                           
                        <?php // echo $form->field($model, 'fileNo') ?>

                       

                        <?php // echo $form->field($model, 'total_water_and_conservancy_amount') ?>

                        <?php // echo $form->field($model, 'tinure') ?>

                        <?php // echo $form->field($model, 'dues_amount') ?>

                        <?php // echo $form->field($model, 'per_month_charges') ?>

                        <?php // echo $form->field($model, 'no_of_months') ?>

                        <?php // echo $form->field($model, 'total_amount_of_current_months') ?>

                        <?php // echo $form->field($model, 'advanced_pay') ?>

                        <?php // echo $form->field($model, 'arrears') ?>

                        <?php // echo $form->field($model, 'arrears_period') ?>

                        <?php // echo $form->field($model, 'total_bill') ?>

                        <?php // echo $form->field($model, 'after_due_date_charges') ?>

                        <?php // echo $form->field($model, 'total_after_due_date') ?>

                        <?php // echo $form->field($model, 'balance_arears') ?>

                        <?php // echo $form->field($model, 'remarks') ?>

                        <?php // echo $form->field($model, 'water_charges_per_month') ?>

                        <?php // echo $form->field($model, 'conservancy_charges_per_month') ?>

                        <?php // echo $form->field($model, 'four_months_water_charges') ?>

                        <?php // echo $form->field($model, 'four_months_conservancy_charges') ?>

                        <div class="col-lg-2">

                 
                         <?= $form->field($model, 'billing_months')->dropDownList( ArrayHelper::map(bill::find()->all(),'billing_months', 'billing_months'), ['prompt'=>'All Tenure', 'name'=>'tenuresearch'])?>

                            </div>
                

                        <?php // echo $form->field($model, 'issue_date') ?>

                        <?php // echo $form->field($model, 'due_date') ?>

               

                        <?php // echo $form->field($model, 'cnic') ?>

                        
                     <div class="col-lg-2"> 

                  <?= $form->field($model, 'sector')->dropDownList( ArrayHelper::map(bill::find()->all(),'subsectorName.name', 'subsectorName.name'), ['prompt'=>'All', 'name'=>'subsector'])?>


                       </div>

                  <!--  <div class="col-lg-2">


                    <?php  echo $form->field($model, 'status')->dropDownList(['1'=>'paid' , '0' => 'pending' ], ['prompt'=>'All', 'name'=>'status'])?>

                    

                       </div> -->

             <!------------------------------ Date Range Picker Starts------------------>

                <div class="col-lg-3">
                    <label>Select Date</label>
                <input type="date"  name="start_date" class="form-control">

                </div>
                <div class="col-lg-3">
                    <label>Select Date</label>
                <input type="date"  name="end_date" class="form-control">

                </div>
           

            <!------------------------------ Date Range Picker Ends------------------>
                 
       
          <div class="col-lg-2"></div>

        

     <div class="col-lg-2">
       
       <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
         </div>


     </div>
       </div>
         </div>
           </div>

    <?php ActiveForm::end(); ?>

views/bill/_reportsearch.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Bill;
use app\models\BillSearch;
use yii\helpers\ArrayHelper;
use kartik\daterange\DateRangePicker; 



/* @var $this yii\web\View */
/* @var $model app\models\BillSearch */
/* @var $form yii\widgets\ActiveForm */
?> 

<div class="bill-search"> 

    <?php $form = ActiveForm::begin([
        'action' => ['overall-report'],
        'method' => 'POST',

    ]); ?>

    <div class="card">
        <div class="row">
            <div class="col-lg-12">

                <div class="row" style="margin: 10px;">


                        <?php // echo $form->field($model, 'consumer_id') ?>

                        

                        <?php // echo $form->field($model, 'total_months_conservancy') ?>

                        <?php //echo $form->field($model, 'water_arrears') ?>

                        <?php // echo $form->field($model, 'water_remarks') ?>

                        

                        <?php // echo $form->field($model, 'cnic') ?>

                        
                           
                        <?php // echo $form->field($model, 'fileNo') ?>

                       

                        <?php // echo $form->field($model, 'total_water_and_conservancy_amount') ?>

                        <?php // echo $form->field($model, 'tinure') ?>

                        <?php // echo $form->field($model, 'dues_amount') ?>

                        <?php // echo $form->field($model, 'per_month_charges') ?>

                        <?php // echo $form->field($model, 'no_of_months') ?>

                        <?php // echo $form->field($model, 'total_amount_of_current_months') ?>

                        <?php // echo $form->field($model, 'advanced_pay') ?>

                        <?php // echo $form->field($model, 'arrears') ?>

                        <?php // echo $form->field($model, 'arrears_period') ?>

                        <?php // echo $form->field($model, 'total_bill') ?>

                        <?php // echo $form->field($model, 'after_due_date_charges') ?>

                        <?php // echo $form->field($model, 'total_after_due_date') ?>

                        <?php // echo $form->field($model, 'balance_arears') ?>

                        <?php // echo $form->field($model, 'remarks') ?>

                        <?php // echo $form->field($model, 'water_charges_per_month') ?>

                        <?php // echo $form->field($model, 'conservancy_charges_per_month') ?>

                        <?php // echo $form->field($model, 'four_months_water_charges') ?>

                        <?php // echo $form->field($model, 'four_months_conservancy_charges') ?>

                        <div class="col-lg-2">

                 
                         <?= $form->field($model, 'billing_months')->dropDownList( ArrayHelper::map(bill::find()->all(),'billing_months', 'billing_months'), ['prompt'=>'All Tenure', 'name'=>'tenuresearch'])?>

                            </div>
                

                        <?php // echo $form->field($model, 'issue_date') ?>

                        <?php // echo $form->field($model, 'due_date') ?>

               

                        <?php // echo $form->field($model, 'cnic') ?>

                        
                    

               <!--    <?= $form->field($model, 'sector')->dropDownList( ArrayHelper::map(bill::find()->all(),'subsectorName.name', 'subsectorName.name'), ['prompt'=>'All', 'name'=>'subsector'])?> -->


                   

                  <!--  <div class="col-lg-2">


                    <?php  echo $form->field($model, 'status')->dropDownList(['1'=>'paid' , '0' => 'pending' ], ['prompt'=>'All', 'name'=>'status'])?>

                    

                       </div> --> 

             <!------------------------------ Date Range Picker Starts------------------>

                <div class="col-lg-3">
                    <label>Select Date</label>
                <input type="date"  name="start_date" class="form-control">

                </div>
                <div class="col-lg-3">
                    <label>Select Date</label>
                <input type="date"  name="end_date" class="form-control">

                </div>
           

            <!------------------------------ Date Range Picker Ends------------------>
                 
       
          <div class="col-lg-2"></div>
          <div class="col-lg-2"></div>

        

     <div class="col-lg-2">
       
       <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
         </div>


     </div>
       </div>
         </div>
           </div>

    <?php ActiveForm::end(); ?>

views/bill/barCode_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\bill;
use yii\helpers\Url;
use kartik\widgets\FileInput;


/* @var $this yii\web\View */
/* @var $model app\models\Bill */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="bill-form">
   

    
 <?php  $form = ActiveForm::begin(['action' => 'updatestatus','options' => ['enctype'=>'multipart/form-data']]); ?>
  <!-- 
 
 <div class="form-group">
    <label for="text">Consumer ID:</label>
    <input type="text" class="form-control" id="c_id">
  </div> -->
  <div class="form-group">
    <label for="text">Bill ID:</label>
    <input type="text" name="bill_id" class="form-control form-control-user" id="b_id">
  </div>
        <input type="hidden" name="check" value="0">
         
        <div class="form-group">
            <div class="custom-control custom-checkbox small">
            <input type="checkbox" class="custom-control-input" id="customCheck" name="check" value="1" >
            <label class="custom-control-label" for="customCheck" style="font-size: 18px">Bill after due date</label>
            </div>
        </div>
  <div class="alert alert-success" id="s-msg" style="display:<?= $dis?>;">
   <strong ><?= $data1?></strong> 
</div>
  
  


  <?= Html::submitButton('Update', ['class' => 'btn btn-success ' , 'name' => 'update-button']) ?>


     

    <?php ActiveForm::end(); ?>

</div>

views/bill/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Bill */

$this->title = 'Create Bill';
$this->params['breadcrumbs'][] = ['label' => 'Bills', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="bill-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/bill/index.php
<?php
ini_set('memory_limit', '-1');
use yii\helpers\Html;

use yii\grid\GridView;
use yii\helpers\Url;
use yii\widgets\pjax;

 
/* @var $this yii\web\View */
/* @var $searchModel app\models\BillSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Bills';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="bill-index">

     <?php 
    if (yii::$app->session->hasFlash('success')) {?>
        <div class="alert alert-success">
   <strong ><?php echo yii::$app->session->getFlash('success');?></strong> 
</div>
       
 <?php   }
?>
 
    <div class="card-header py-3 panel" style="">
        <!--<?= Html::a('+ Add Bill', ['create'], ['class' => 'btn btn-success']) ?>-->
    </div>


    <?php echo $this->render('_search', ['model' => $searchModel]); ?>
   
     <?= GridView::widget([
        'dataProvider' => $dataProvider,
        // 'filterModel' => $searchModel,
        'columns' => [
            

            'id',
            [    'header'=> 'Consumer Name',
                'attribute'=>'consumer_id',
                'value'=>'consumerId.allottee_name',
            ],

      

            // 'cnic',
           
            [
                'header'=> 'File No',
                'attribute'=>'consumer_id',
                'value'=> 'fileNo.file_no',
            ],

            [    'header'=> 'Street No',
                'attribute'=>'consumer_id',
                'value'=>'consumerId.street_no',
            ],

            [    'header'=> 'House No',
                'attribute'=>'consumer_id',
                'value'=>'consumerId.house_no',
            ],

            [    'header'=> 'Sub Sector',
                'attribute'=>'sector',
                'value'=>'subsectorName.name',
            ],

            [    'header'=> 'Tenure',
                'attribute'=>'tinure',
                'value'=>'tenureName.tenure_name',
            ],

            


            [    
                'header'=>'Arrears',
                'attribute'=>'arrear',
                'value'=>function ($model) {
                 
                return($model->arrears+$model->debit);

                },

            ],


            'total_bill',
            'payment',

             [  
                'header' => 'Status',
                'attribute' => 'status',
                'value' => function ($model, $widget) {
                    if($model->status == 1){
                return "<span class=\"badge badge-pill badge-success\"> Paid </span>";
                    }

                     else{
                 return "<span class=\"badge badge-pill badge-danger\"> Pending </span>";
                    }
                    
                    },
                    'format' => 'raw',
                ],


            
           
           
            // 'status',
            //'conservancy_amount',
            //'total_water_and_conservancy_amount',
            //'tinure',
            //'dues_amount',
            //'per_month_charges',
            //'no_of_months',
            //'total_amount_of_current_months',
            //'advanced_pay',
          
            //'barcode_id',
            //'arrears_period',
            //'total_bill',
            //'after_due_date_charges',
            //'total_after_due_date',
            //'balance_arears',
            //'remarks',
            //'water_charges_per_month',
            //'conservancy_charges_per_month',
            //'four_months_water_charges',
            //'four_months_conservancy_charges',
            //'billing_months',
            //'issue_date',
            //'due_date',
            //'reference_no',
          ['class' => 'yii\grid\ActionColumn',
            'header'=>'Action',
            'headerOptions' => ['width' => '80'],
            'template' => '{View}{Update}{Delete}',
            'buttons'=> [
                'Delete' => function ($url,$model,$key){
                    return html::a('<i class="fa fa-trash" style="font-size:16px;color:#F05550 "></i>', url::to(['/bill/delete?id='.$model->id])); 
                },
                'View' => function ($url,$model,$key){
                    return html::a('<i class="fa fa-eye" style="font-size:16px;color:#00cc66 "></i>',Url::to(['/bill/view', 'id' => $model->id]),);
                },
                'Update' => function ($url,$model,$key){
                    return html::a('<i class="fa fa-edit" style="font-size:16px;color:#4A94D2 "></i>',url::to(['/bill/update?id='.$model->id]));
                }
            ]
        ], 
        ],
    ]); ?>


           
     
</div>

views/bill/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Bill */

$this->title = 'Update Bill: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Bills', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="bill-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>