models/BillGenerate.php
<?php

namespace app\models;


use Yii;

/**
 * This is the model class for table "bill_generate".
 *
 * @property int $id
 * @property int $tenure_id
 * @property int $status
 * @property int $print_status
 * @property string $created_on
 * @property int $created_by
 * @property string|null $updated_on
 * @property int|null $updated_by
 */
class BillGenerate extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'bill_generate';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [[ 'status', 'print_status', 'created_on', 'created_by'], 'required'],
            [[ 'status', 'print_status', 'created_by', 'updated_by'], 'integer'],
            [['created_on', 'updated_on','sector_id','tenure_id','file_no'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tenure_id' => 'Tenure Name',
            'sector_id' => 'Sector Name',
            'status' => 'Status',
            'file_no'=>'File No',
            'print_status' => 'Print Status',
            'created_on' => 'Created On',
            'created_by' => 'Created By',
            'updated_on' => 'Updated On',
            'updated_by' => 'Updated By',
        ];
    }

    public function gettenureId()
    {
        return $this->hasOne(Tenure::className(),['id' => 'tenure_id']);
    }
    
}

models/BillGenerateController.php
<?php

namespace app\controllers;
// require "vendor/phpmailer/autoload.php";
use app\models\Bill;
use app\models\Category;
use app\models\ConsumerServices;
use app\models\Services;
use app\models\Sectors;
use app\models\Plot;
use app\models\Tenure;
use app\models\Sms;
use Yii;
use app\models\BillGenerate;
use app\models\BillGenerateSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\Activity;
use CodeItNow\BarcodeBundle\Utils\BarcodeGenerator; 





/**
 * BillGenerateController implements the CRUD actions for BillGenerate model.
 */
class BillGenerateController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        $behaviors['access'] = [
            'class' => AccessControl::className(),
            'rules' => [
                [

                    'allow' => true,
                    'roles' => ['@'],
                    'matchCallback' => function ($rule, $action) {

                        // $module                 = Yii::$app->controller->module->id;
                        $action                 = Yii::$app->controller->action->id;
                        $controller         = Yii::$app->controller->id;
                        $route                     = "$controller/$action";
                        $post = Yii::$app->request->post();


                        if($route=='BillGenerate/validate')
                        {
                            return true;
                        }
                        else if (\Yii::$app->user->can($route)) {
                            return true;
                        }


                    }
                ], 
            ], 
        ];

        return $behaviors;
    }

    /**
     * Lists all BillGenerate models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BillGenerateSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single BillGenerate model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)

    {
       $tenure = \app\models\BillGenerate::find()->select('tenure_id')->from('bill_generate')->where('id='.$id)->one();

        $this->layout = 'generatebill';
         $bills = \app\models\Bill::find()->Where(['tinure'=>$tenure->tenure_id])->all();
       // // $bills;
       //   echo "<pre>";
       //   print_r($bills);
       //   exit();
        return $this->render('view', [
            'model' => $bills,

        ]); 
    }
    
     public function actionSectorView()

    {   
        if (isset($_POST['submit'])) {
        
        $tenure = $_POST['tenure'];
        $sector = $_POST['sector'];
        

       $tenure = \app\models\BillGenerate::find()->select('tenure_id')->from('bill_generate')->where('id='.$tenure)->one();

        $this->layout = 'generatebill';
         $bills = \app\models\Bill::find()->Where(['sector'=>$sector])->all();
       // // $bills;
       //   echo "<pre>";
       //   print_r($bills);
       //   exit();
     }
        return $this->render('view', [
            'model' => $bills,

        ]); 
    }

   
    
     public function actionConsumercreate()
    {
 
        $model = new BillGenerate();

        if ($model->load(Yii::$app->request->post())  ) {
            $consumer = Plot::find()->where(['file_no'=>$_POST['BillGenerate']['file_no']])->all();
            // echo "<pre>";
            // print_r($consumer);
            // exit();
            if (!empty($consumer)) {
            
            foreach ($consumer as $k=>$val){
                $cat_detail = Category::findOne($val->cat_id);
                $sector_detail = Sectors::findall($val->sector);
                // $tinure_detail = Tenure::findall();
                // echo "<pre>";
                // print_r($tinure_detail);
                // exit();
                $bill = New Bill(); 
                $bill->consumer_id = $val->id;
                $bill->cnic = $val->cnic;
                $bill->email= $val->email;
                $bill->phone= $val->phone;
                $bill->tinure = $_POST['BillGenerate']['tenure_id']; 
                $tinure_detail = Tenure::findOne($bill->tinure);
                $bill->no_of_months = $tinure_detail->t_interval;

                $charge=0;
                $services = ConsumerServices::find()->where(['consumer_id'=>$val->id] )->all();
                        foreach ($services as $val1)
                        {
                            $service = Services::find()->select('charges')->from('services')->where(['id'=>$val1->service_id])->all();  

                        foreach ($service as $serve)
                        {
                            $charge += $serve['charges']* $tinure_detail->t_interval;
    
                        }} 
                $service_charges = Services::find()->select(['water_bill'=>'service_name','charges'])->from('services')->one();
                             
                $bill->water_bill= $charge;

                $count=0;
                $count = \app\models\Bill::find()->where('consumer_id='.$val->id )->count();
             

                    if($count>0) 
                    {
                        $arrears = \app\models\Bill::find()->select('total_bill,total_after_due_date,status')->from('bill')->Where(['consumer_id'=>$bill->consumer_id]) ->limit(1)->orderBy(['id' =>SORT_DESC])->one();
                        if ($arrears->status==0)
                        {
                           $bill->arrears =$arrears->total_after_due_date; 
                        }
                        else
                        {
                            $bill->arrears=0;
                        }   
                    }
                    else
                    {
                         $bill->arrears = 0 ;
                    }

                //$bill->conservancy_amount = $cat_detail->conservancy*$tinure_detail->t_interval;

                $covered_area = round($val->covered_area);
                $per_month_amount = round($covered_area/12);
                $tenure_amount =  $per_month_amount*$tinure_detail->t_interval;

                $bill->conservancy_amount=  round($tenure_amount);

                $bill->total_water_and_conservancy_amount = $bill->conservancy_amount+$charge;

                $bill->per_month_charges = $bill->total_water_and_conservancy_amount/$tinure_detail->t_interval;
            
                // $bill->sector = $_POST['BillGenerate']['sector_id']; 

                // check credit availability  
                if (!empty($val->balance)) 
                { 
                    $bill->advanced_pay = $val->balance;
                }
                else
                { 
                    $bill->advanced_pay=0;
                }

                // check debiit availability 
              

                $bill->instalment= $val->instalment;

                if ($val->debit>=$bill->instalment) {
                   
                if ($bill->instalment<=0) {
                     $bill->debit = $val->debit;
                     \Yii::$app->db->createCommand("UPDATE plot SET debit= '0' WHERE id=$val->id")->execute();


                }
                else
                {
                   $bill->instalment= $val->instalment;
                   $update= abs($val->debit - $bill->instalment);
                   $val->debit = $update;
                
                   \Yii::$app->db->createCommand("UPDATE plot SET debit= $val->debit  WHERE id=$val->id")->execute();
                   // $bill->debit = $val->debit ;
                   if ($val->debit<$val->instalment) {
                    \Yii::$app->db->createCommand("UPDATE plot SET instalment= '0' WHERE id=$val->id")->execute();
                   }
                }}
                else{

                    $bill->debit=$val->debit;
                     $query = \Yii::$app->db->createCommand("UPDATE plot SET instalment= '0' WHERE id=$val->id")->execute();
                }


                // Bill calcltaions 
               
                $bill->advanced_pay = $val->balance;
                if (!empty($bill->advanced_pay)) 
                {  
                    // if there is credit availabe && greater than bill charges  then this script runs.....
                    if ($bill->advanced_pay >  $cat_detail->conservancy+$bill->arrears+$charge)
                    {
                        $bill->total_bill=  abs($cat_detail->conservancy+$bill->arrears+$charge - $bill->advanced_pay +  $bill->debit+$bill->instalment);
                        $total = $bill->total_bill;

                        $bill->total_bill= 0;

                        \Yii::$app->db->createCommand("UPDATE plot SET balance=  $total  WHERE id=$val->id")->execute();
                    }
                    // if there is credit availabe && less than bill charges  then this script runs 
                    else
                    {
                        $bill->total_bill=  abs($cat_detail->conservancy+$bill->arrears+$bill->instalment+$charge - $bill->advanced_pay);
                        $total = $bill->total_bill;
                        
                        $bill->total_bill = $total;
                        \Yii::$app->db->createCommand("UPDATE plot SET balance= '0'  WHERE id=$val->id")->execute();

                        // \Yii::$app->db->createCommand("UPDATE plot SET debit= '0'  WHERE id=$val->id")->execute();

                    }
                }
                // if there is no credit available 
                else{

views/bill-generate/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Tenure;
use app\models\Sectors;

/* @var $this yii\web\View */
/* @var $model app\models\BillGenerate */
/* @var $form yii\widgets\ActiveForm */
?> 

<div class="bill-generate-form">

    <div class="card mb-4">
        <div class="card-header">
            Bill Genrate
        </div>
        <div class="card-body">
            <?php $form = ActiveForm::begin(); ?>
            <?= $form->field($model, 'tenure_id')->dropDownList(
    		ArrayHelper::map(tenure::find()->all(),'id', 'tenure_name'),
    		['prompt'=>'Select Tenure'])?>
              
            <div class="form-group">
                    <label for="date">Due Date</label>
                    <input type="Date" class="form-control" name ="due-date" id="date">
                </div>
             

            <?= Html::submitButton(Yii::t('app', 'Genrate Bill'), ['class' => 'btn btn-primary']) ?>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

 

views/bill-generate/_formconsumer.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Tenure;
use app\models\Sectors;

/* @var $this yii\web\View */
/* @var $model app\models\BillGenerate */
/* @var $form yii\widgets\ActiveForm */
?> 

<div class="bill-generate-form">
 
    <div class="card mb-4">
        <div class="card-header">
            Bill Genrate
        </div>
        <div class="card-body">
             <?php $form = ActiveForm::begin(); ?>
              <?= $form->field($model, 'file_no')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'tenure_id')->dropDownList(
            ArrayHelper::map(tenure::find()->where(['status'=>1])->all(),'id', 'tenure_name'),
            ['prompt'=>'Select Tenure'])?>

           
           

                <div class="form-group">
                    <label for="date">Due Date</label>
                    <input type="Date" class="form-control" name ="due-date" id="date">
                </div>
             

            <?= Html::submitButton(Yii::t('app', 'Genrate Bill'), ['id'=>'getData','class' => 'btn btn-primary']) ?>
            <div id="result" style="margin-top:10px"> </div>
            <div id="loader" style="display:none;">
            <br>
              <img src="\billing\web\img\ajax-loader.gif"/>
             </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            
 <script>
  $(document).ready(function(){

    $("#getData").on("click",function(){

     $.ajax({

        type:"GET",
        url: "/billing/web/bill-generate/create",

        beforeSend: function(){
            $("#loader").show();
            $("#result").html("In Progress...");
        },

        complete:function(){
            $("#loader").show();
        },

        success:function(){
           // $("#loader").hide();
            //$("#result").html("Please Wait!");
            
        },

        error:function(){
            $("#loader").hide();
            $("#result").html("Some Error Occured");
           
        }

     });


    });

  });
</script>

views/bill-generate/_formsector.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Tenure;
use app\models\Sectors;

/* @var $this yii\web\View */
/* @var $model app\models\BillGenerate */
/* @var $form yii\widgets\ActiveForm */
?> 

<div class="bill-generate-form">

    <div class="card mb-4">
        <div class="card-header">
            Bill Genrate
        </div>
        <div class="card-body">
             <?php $form = ActiveForm::begin(); ?>
            <?= $form->field($model, 'tenure_id')->dropDownList(
            ArrayHelper::map(tenure::find()->all(),'id', 'tenure_name'),
            ['prompt'=>'Select Tenure'])?>
           
            <?= $form->field($model, 'sector_id')->dropDownList(
    		ArrayHelper::map(sectors::find()->all(),'id', 'sector_name'),
    		['prompt'=>'Select Sector'])?>
                <div class="form-group">
                    <label for="date">Due Date</label>
                    <input type="Date" class="form-control" name ="due-date" id="date">
                </div>
             

            <?= Html::submitButton(Yii::t('app', 'Genrate Bill'), ['class' => 'btn btn-primary']) ?>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/bill-generate/_formsubsector.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm; 
use yii\helpers\ArrayHelper;
use app\models\Tenure;
use app\models\SubSectors;

/* @var $this yii\web\View */
/* @var $model app\models\BillGenerate */
/* @var $form yii\widgets\ActiveForm */
?> 

<div class="bill-generate-form">

    <div class="card mb-4">
        <div class="card-header">
            Bill Genrate
        </div>
        <div class="card-body">
             <?php $form = ActiveForm::begin(); ?>
            <?= $form->field($model, 'tenure_id')->dropDownList(
            ArrayHelper::map(tenure::find()->where(['status'=>1])->all(),'id', 'tenure_name'),
            ['prompt'=>'Select Tenure'])?>
           
            <?= $form->field($model, 'sector_id')->dropDownList(
            ArrayHelper::map(SubSectors::find()->where(['status'=>1])->all(),'name', 'name'),
            ['prompt'=>'Select Sector'])?>
                <div class="form-group">
                    <label for="date">Due Date</label>
                    <input type="Date" class="form-control" name ="due-date" id="date">
                </div>
             

            <?= Html::submitButton(Yii::t('app', 'Genrate Bill'), ['id'=>'getData','class' => 'btn btn-primary']) ?>
            <div id="result" style="margin-top:10px"> </div>
            <div id="loader" style="display:none;">
            <br>
              <img src="\billing\web\img\ajax-loader.gif"/>
             </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            
 <script>
  $(document).ready(function(){

    $("#getData").on("click",function(){

     $.ajax({

        type:"GET",
        url: "/billing/web/bill-generate/create",

        beforeSend: function(){
            $("#loader").show();
            $("#result").html("In Progress...");
        },

        complete:function(){
            $("#loader").show();
        },

        success:function(){
           // $("#loader").hide();
            //$("#result").html("Please Wait!");
            
        },

        error:function(){
            $("#loader").hide();
            $("#result").html("Some Error Occured");
           
        }

     });


    });

  });
</script>

views/bill-generate/_search (1).php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Bill;
use app\models\BillSearch;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\BillGenerateSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="bill-generate-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <div class="card">
        <div class="row">
            <div class="col-lg-12">

                <div class="row" style="margin: 10px;">


                 <div class="col-lg-3">

              <?= $form->field($model, 'tenure_id')->dropDownList( ArrayHelper::map(bill::find()->all(),'billing_months', 'billing_months'), ['prompt'=>'All Tenure'])?>

                </div>

                <!--  <div class="col-lg-2">

                    <?= $form->field($model, 'status') ?>

                </div> -->
<!-- 
                 <div class="col-lg-2">

                    <?= $form->field($model, 'print_status') ?>

                </div> -->

               
                    <?php // echo $form->field($model, 'created_by') ?>

                    <?php // echo $form->field($model, 'updated_on') ?>

                    <?php // echo $form->field($model, 'updated_by') ?>
                     <div class="col-lg-2"></div>
                       <div class="col-lg-2">
                       </div>
                        <div class="col-lg-2">
                       </div>
                            <div class="col-lg-2">
                       </div>
                         <div class="col-lg-3">
                       </div>

    <div class="col-lg-2">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>
</div>
</div>
</div>
</div>

    <?php ActiveForm::end(); ?>

</div>

views/bill-generate/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Bill;
use app\models\BillSearch;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\BillGenerateSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="bill-generate-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <div class="card">
        <div class="row">
            <div class="col-lg-12">

                <div class="row" style="margin: 10px;">


                 <div class="col-lg-3">

              <?= $form->field($model, 'tenure_id')->dropDownList( ArrayHelper::map(bill::find()->all(),'billing_months', 'billing_months'), ['prompt'=>'All Tenure'])?>

                </div>

                <!--  <div class="col-lg-2">

                    <?= $form->field($model, 'status') ?>

                </div> -->
<!-- 
                 <div class="col-lg-2">

                    <?= $form->field($model, 'print_status') ?>

                </div> -->

               
                    <?php // echo $form->field($model, 'created_by') ?>

                    <?php // echo $form->field($model, 'updated_on') ?>

                    <?php // echo $form->field($model, 'updated_by') ?>
                     <div class="col-lg-2"></div>
                       <div class="col-lg-2">
                       </div>
                        <div class="col-lg-2">
                       </div>
                            <div class="col-lg-2">
                       </div>
                      

    <div class="col-lg-2">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>
</div>
</div>
</div>
</div>

    <?php ActiveForm::end(); ?>

</div>

views/bill-generate/consumercreate.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\BillGenerate */

$this->title = Yii::t('app', 'Create Bill Generate');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Bill Generates'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="bill-generate-create">


    <?= $this->render('_formconsumer', [
        'model' => $model,
    ]) ?>

   

</div> 

views/bill-generate/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\BillGenerate */

$this->title = Yii::t('app', 'Create Bill Generate');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Bill Generates'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="bill-generate-create">


    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

   

</div> 

views/bill-generate/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
 
/* @var $this yii\web\View */
/* @var $searchModel app\models\BillGenerateSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Bill Generates');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="bill-generate-index">
 
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Generate Tinure Bills'), ['create'], ['class' => 'btn btn-success']) ?>  &nbsp;&nbsp;

        <?= Html::a(Yii::t('app', 'Generate Sector Bills'), ['sectorcreate'], ['class' => 'btn btn-success']) ?> &nbsp;&nbsp;

         <?= Html::a(Yii::t('app', 'Generate Sub-Sector Bills'), ['subsectorcreate'], ['class' => 'btn btn-success']) ?> &nbsp;&nbsp;

        <?= Html::a(Yii::t('app', 'Generate Consumer Bills'), ['consumercreate'], ['class' => 'btn btn-success']) ?>
    
        <div class="alert">
  <!-- <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> -->
  <?php $var ?>
</div>  
    </p>

    <?php  echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        // 'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

           
            [    
                'attribute'=>'tenure_id',
                'value'=>'tenureId.tenure_name',
            ],
           
            //'selectop',
            [    
                
                'attribute'=>'status',
                'value'=>function ($model, $widget) {
                 
                    if($model->status ==1){
                        return( "All bills generated");
                    } else{
                        return( "pending");
                    }

                },

            ],
            // 'status',
            // 'print_status',
                     [    
                
                'attribute'=>'print_status',
                'value'=>function ($model, $widget) {
                 
                    if($model->print_status ==1){
                        return( "All bills printed");
                    } else{
                        return( "pending");
                    }

                },

            ],
            [
                'attribute'=>'created_on',
                'format' => ['datetime', 'php:d-m-Y H:i:s']
            ],
            //'created_by',
            //'updated_on',
            //'updated_by',

             ['class' => 'yii\grid\ActionColumn',
            'header'=>'Action',
            'headerOptions' => ['width' => '80'],
            'template' => '{View}{Update}{Delete}',
            'buttons'=> [
                
                'View' => function ($url,$model,$key){
                    return html::a('<i class="fa fa-eye" style="font-size:16px;color:#00cc66 "></i>',Url::to(['/bill-generate/view', 'id' => $model->id]),);
                },
               
            ]
        ], 
        
        ],
    ]); ?>


</div>

views/bill-generate/sectorcreate.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\BillGenerate */

$this->title = Yii::t('app', 'Create Bill Generate');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Bill Generates'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="bill-generate-create">


    <?= $this->render('_formsector', [
        'model' => $model,
    ]) ?>

   

</div> 

views/bill-generate/subsectorcreate.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\BillGenerate */

$this->title = Yii::t('app', 'Create Bill Generate');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Bill Generates'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="bill-generate-create">


    <?= $this->render('_formsubsector', [
        'model' => $model,
    ]) ?>

   

</div> 

views/bill-generate/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\BillGenerate */

$this->title = Yii::t('app', 'Update Bill Generate: {name}', [
    'name' => $model->id,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Bill Generates'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="bill-generate-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>